### PR TITLE
Add support for pausing the dismiss timer

### LINKED ISSUE #25: Toasts are dismissed without being shown when there are more toasts than `maxVisibleToasts`
I suppose I could handle this myself, but I think any users would appreciate the change.

My suggestion is that the duration for a toast should start when it is the top toast on the stack, instead of when it's created.

### PR DESCRIPTION
**Pull request by dokar3**
Resolve #25 

### Example

```kotlin
Toaster(
    state = toaster,
    dismissPause = ToastDismissPause.OnNotFront,
)
```

### CODE REVIEW

**Comment by sproctor** [comment]
The idea is great, but something happens after the first dismiss and then all of the toasts are unpaused.

[1, 2, 3, 4]
delay
[2, 3, 4]
delay
[]

**Comment by dokar3** [comment]
> The idea is great, but something happens after the first dismiss and then all of the toasts are unpaused.

That's weird, they did work in the sample and tests.
https://github.com/dokar3/compose-sonner/pull/27/files#diff-ab3d286a6012edfb480afc76bc3a36eb528621ae0c67bbb9cc99087226c3c955R45-R66

> [1, 2, 3, 4]
> delay
> [2, 3, 4]
> delay
> []

Could you provide a sample code to reproduce this?

**Comment by sproctor** [comment]
Other than that bug, the last release is great. Thanks so much for your changes today.

**Comment by dokar3** [comment]
> Other than that bug, the last release is great. Thanks so much for your changes today.

Happy to help! Will check that later.

**Pull request merged**
